import * as THREE from './assets/13-three.min.js';
for(const [selector,type] of [['.infrastructure-art','architecture'],['.risk-art','risk'],['.process-art','process']]){
const figure=document.querySelector(selector),img=figure.querySelector('img'),stage=document.createElement('div');stage.className='chapter-visual';img.before(stage);stage.append(img);const canvas=document.createElement('canvas');canvas.className='chapter-canvas';canvas.setAttribute('aria-label',`Illustrative ${type} concept, not actual product hardware`);stage.append(canvas);
const scene=new THREE.Scene(),cam=new THREE.PerspectiveCamera(33,1,.1,100),r=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});r.setPixelRatio(Math.min(devicePixelRatio,2));r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=1.25;
const rig=new THREE.Group();scene.add(rig);const objects=[],white=new THREE.MeshStandardMaterial({color:0xe8eff6,metalness:.22,roughness:.27}),blue=new THREE.MeshStandardMaterial({color:0x628dbf,metalness:.48,roughness:.22}),glass=new THREE.MeshPhysicalMaterial({color:0xb9d8f1,roughness:.14,metalness:.12,transparent:true,opacity:.45,side:THREE.DoubleSide}),ink=new THREE.MeshStandardMaterial({color:0x142e4b,metalness:.4,roughness:.24});
const add=(geo,mat,x,y,z,parent=rig)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);parent.add(m);return m};const box=(a,b,c,mat,x,y,z,parent)=>add(new THREE.BoxGeometry(a,b,c),mat,x,y,z,parent);
if(type==='architecture'){for(let j=0;j<4;j++){const g=new THREE.Group();rig.add(g);box(3.2,.06,2.15,glass,0,0,0,g);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(3.2,.06,2.15)),new THREE.LineBasicMaterial({color:0x9ec1e4}));g.add(edges);for(let n=0;n<8;n++)box(.65,.04,.08,n%2?blue:white,(n%2-.5)*1.9,.045,(Math.floor(n/2)-1.5)*.42,g);g.position.y=(j-1.5)*.64;objects.push(g)}box(.72,2.55,.72,ink,0,0,0);}
if(type==='risk'){for(let i=0;i<4;i++){const x=(i-1.5)*.85,h=[1.7,2.15,1.5,2.55][i];const g=new THREE.Group();rig.add(g);box(.52,h,.52,i%2?blue:ink,0,h/2-1.2,0,g);box(.58,.065,.58,white,0,h-1.18,0,g);add(new THREE.TorusGeometry(.25,.055,12,48),white,0,h-1.0,.37,g).rotation.x=.2;g.position.x=x;objects.push(g)}box(3.9,.10,1.7,white,0,-1.29,0);}
if(type==='process'){for(let i=0;i<7;i++){const g=new THREE.Group();rig.add(g);const x=(i-3)*.58,y=(i-3)*.25;box(.52,.5,.68,i%2?blue:white,x,y,0,g);box(.27,.014,.33,ink,x,y+.256,0,g);objects.push(g)}box(4.6,.025,.03,blue,0,-1.16,.5);}
scene.add(new THREE.HemisphereLight(0xeaf5ff,0x173552,3));for(const [color,intensity,x,y,z]of[[0xffffff,6,3,5,5],[0x6daeff,5,-4,2,2],[0xb5dbff,5,1,3,-4]]){const l=new THREE.DirectionalLight(color,intensity);l.position.set(x,y,z);scene.add(l)}
cam.position.set(type==='architecture'?4.7:3.3,type==='architecture'?3.7:2.7,7.3);cam.lookAt(0,0,0);let visible=false,w=0,h=0,frames=0;new IntersectionObserver(e=>visible=e[0].isIntersecting,{rootMargin:'100px'}).observe(stage);const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;function loop(t){if(visible){const q=stage.getBoundingClientRect();if(q.width!==w||q.height!==h){w=q.width;h=q.height;r.setSize(w,h,false);cam.aspect=w/h;cam.updateProjectionMatrix()}const s=Math.max(0,Math.min(1,(innerHeight-q.top)/(innerHeight+q.height))),time=reduced?0:t/1000;rig.rotation.y=-.22+Math.sin(time*.3)*.08+s*.22;rig.rotation.z=type==='process'?-.06:0;objects.forEach((g,i)=>{if(type==='architecture')g.position.y=(i-1.5)*(.64+s*.18);else g.position.y=Math.sin(time*.7+i*.8)*.055});r.render(scene,cam);frames++}requestAnimationFrame(loop)}loop(0);window.__chapterGL=window.__chapterGL||{};window.__chapterGL[type]={get frames(){return frames},renderer:r};
}
