(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];gsap.registerPlugin(ScrollTrigger);const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;window.__motionScenes=[];window.__demoState={scenario:0,phase:0};window.__lenis=null;if(!reduce){const l=window.__lenis=new Lenis({duration:1.1,smoothWheel:true});l.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>l.raf(t*1000));gsap.ticker.lagSmoothing(0)}
const inputs={macro:['Economic context','An economic release enters the data stage. Predefined rules evaluate it alongside related context before an eligible instruction can reach the execution platform.'],rates:['Rate context','Central bank rates enter the data stage. The rule-processing stage evaluates their currency and economic context before any eligible platform instruction.'],risk:['Risk context','Market-risk inputs enter the data stage. Defined controls are checked in rule processing before an eligible instruction reaches MetaTrader or cTrader.']};$$('[data-input]').forEach(b=>b.addEventListener('click',()=>{$$('[data-input]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const data=inputs[b.dataset.input];$('#input-title').textContent=data[0];$('#input-detail').textContent=data[1];window.__activeInput=b.dataset.input;if(!reduce)gsap.fromTo('.output-stage i',{scale:1},{scale:1.8,duration:.45,yoyo:true,repeat:1})}));
const scenarios=[['Normal conditions','Inputs arrive, checks run, and eligible instructions proceed through the defined workflow.'],['Volatility shock','The illustration routes incoming signals through a risk-control checkpoint before a decision can proceed.'],['Connection interruption','The illustration pauses the execution path while connectivity is reviewed. It is not a verified product behavior.']];$$('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{$$('[data-scenario]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));window.__demoState.scenario=Number(b.dataset.scenario);$('#scenario-title').textContent=scenarios[window.__demoState.scenario][0];$('#scenario-detail').textContent=scenarios[window.__demoState.scenario][1]}));$('#phase').addEventListener('input',e=>{window.__demoState.phase=+e.target.value;$('#phase-name').textContent=+e.target.value<34?'Observe':+e.target.value<67?'Apply controls':'Review'});
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=$(a.getAttribute('href'));if(target){e.preventDefault();window.__lenis?window.__lenis.scrollTo(target,{offset:-35}):target.scrollIntoView({behavior:reduce?'instant':'smooth'})}}));
const film=$('.film-stage video'),filmButton=$('.film-start');film.muted=true;film.defaultMuted=true;film.playsInline=true;
const revealFilm=()=>{filmButton.hidden=false;filmButton.textContent=film.readyState<2?'Load / play film ↗':'Play film ↗'};
const startFilm=()=>{const promise=film.play();if(promise)promise.then(()=>{filmButton.hidden=true}).catch(revealFilm)};
const phone=matchMedia('(max-width:650px)').matches;film.poster=phone?'assets/10-v9-poster-phone.webp':'assets/5-v8-poster-desktop.webp';film.src=phone?'assets/9-v9-hero-phone.mp4':'assets/4-v8-hero-desktop.mp4';film.preload='auto';film.load();
film.addEventListener('canplay',startFilm);film.addEventListener('playing',()=>{filmButton.hidden=true});film.addEventListener('error',revealFilm);film.addEventListener('stalled',revealFilm);
setTimeout(()=>{if(film.paused||film.readyState<2)revealFilm()},2200);
filmButton.addEventListener('click',()=>{if(film.readyState===0)film.load();startFilm()});document.addEventListener('touchstart',startFilm,{once:true,passive:true});document.addEventListener('pointerdown',startFilm,{once:true,passive:true});
window.addEventListener('load',()=>ScrollTrigger.refresh());window.__motionReady=true;})();
(()=>{const q=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;all('[data-service]').forEach(b=>b.addEventListener('click',()=>{all('[data-service]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));all('.service-panel').forEach(x=>x.hidden=x.id!==b.dataset.service);ScrollTrigger.refresh()}));const mq=matchMedia('(min-width:651px)'),disclosures=()=>{all('.mobile-disclosure').forEach(d=>d.open=mq.matches);ScrollTrigger.refresh()};disclosures();mq.addEventListener('change',disclosures);all('details').forEach(d=>d.addEventListener('toggle',()=>ScrollTrigger.refresh()));const menu=q('.menu-toggle'),nav=q('#phone-nav');menu.addEventListener('click',()=>{const opened=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(opened));nav.hidden=!opened});all('#phone-nav a').forEach(a=>a.addEventListener('click',()=>{nav.hidden=true;menu.setAttribute('aria-expanded','false')}));if(reduced){q('video').pause();return}
const add=(name,target,vars,trigger=target,options={})=>{const el=typeof target==='string'?q(target):target;if(!el)return;const tr=typeof trigger==='string'?q(trigger):trigger;window.__motionScenes.push({name,target:el.className?.baseVal||el.className||el.tagName,trigger:tr?.id||tr?.className});gsap.to(el,{...vars,ease:'none',scrollTrigger:{trigger:tr,start:'top bottom',end:'bottom top',scrub:.7,...options}})};
add('film inward zoom','.film-stage video',{scale:1.5},'.hero',{start:'top top',end:()=>'+='+innerHeight*.95,pin:true,anticipatePin:1,invalidateOnRefresh:true});add('hero framing','.hero-shade',{scaleY:1.12},'.hero');add('depth foot','.hero-foot',{x:8},'.hero');
all('.chapter-head').forEach((el,i)=>{const line=document.createElement('i');line.className='chapter-line';line.setAttribute('aria-hidden','true');line.style.cssText='position:absolute;left:6vw;right:6vw;top:88px';el.closest('section').append(line);add('chapter rule '+i,line,{scaleX:.12},el)});all('main>.section').forEach((section,i)=>add('chapter overlap '+i,section,{borderTopLeftRadius:30,borderTopRightRadius:30},section,{start:'top bottom',end:'top 30%'}));
all('figure').forEach((f,i)=>{add('image depth '+i,f.querySelector('img'),{y:-12,scale:1.035},f);add('image framing '+i,f,{rotationZ:i%2?.8:-.8},f)});all('.context-points article,.control-grid article,.risk-grid article,.process-list article').forEach((a,i)=>{const line=document.createElement('i');line.className='chapter-line';line.setAttribute('aria-hidden','true');a.append(line);add('individual trace '+i,line,{scaleX:.08},a)});
all('.flow-path').forEach((p,i)=>{const len=p.getTotalLength();p.style.strokeDasharray=len;p.style.strokeDashoffset=len;add('signal path '+i,p,{strokeDashoffset:0},'.flow-lab',{start:'top 75%',end:'bottom 35%'})});all('.data-pulse').forEach((p,i)=>add('context pulse '+i,p,{x:70+20*i},'.flow-lab'));all('.flow-badge rect').forEach((p,i)=>add('node precision '+i,p,{strokeWidth:2},'.flow-lab'));add('core orbit','.core-orbit',{rotation:90,svgOrigin:'450 230'},'.flow-lab');add('ownership boundary','.ownership-glyph>i',{scaleY:.45},'.control');add('ownership label','.ownership-boundary',{y:-10},'.control');add('infrastructure lens','.infrastructure-art img',{filter:'brightness(1.12)'},'.infrastructure');add('stress field depth','#stress-field',{scale:1.08},'.stress');add('stress frame','.stress-visual',{borderRadius:24},'.stress');add('closing orbit one','.closing-orbit i',{rotationZ:70},'.closing');add('closing orbit two','.closing-orbit i:nth-child(2)',{rotationY:65},'.closing');add('closing orbit three','.closing-orbit i:nth-child(3)',{rotationX:60},'.closing');
gsap.matchMedia().add('(min-width:1100px)',()=>{const stage=q('.engine-story'),t=gsap.timeline({scrollTrigger:{trigger:stage,start:'top 7%',end:()=>'+='+innerHeight*.65,scrub:.7,pin:true,anticipatePin:1,invalidateOnRefresh:true}});t.fromTo('.engine-frame',{rotationY:18,rotationX:4,y:45,scale:.84},{rotationY:0,rotationX:0,y:0,scale:1,duration:.7,ease:'none'}).to('.engine-frame',{rotationY:-6,scale:1.025,duration:.3,ease:'none'});window.__motionScenes.push({name:'engine spatial chapter',target:'engine-frame',trigger:'engine-story'})});window.addEventListener('load',()=>ScrollTrigger.refresh());window.__v7Ready=true;
})();
(()=>{if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;const q=s=>document.querySelector(s);const timeline=gsap.timeline({scrollTrigger:{trigger:'.ownership-layout',start:'top 75%',end:'bottom 30%',scrub:.6}});timeline.fromTo('.ownership-glyph>i',{scaleY:.35},{scaleY:1,ease:'none',duration:1}).fromTo('.ownership-glyph>span:first-child',{x:15},{x:0,ease:'none',duration:1},0).fromTo('.ownership-glyph>span:nth-child(3)',{x:-15},{x:0,ease:'none',duration:1},0);window.__motionScenes.push({name:'non custodial separation',target:'ownership-glyph',trigger:'ownership-layout'});gsap.matchMedia().add('(min-width:1100px)',()=>{gsap.fromTo('.risk-art',{rotationY:-14,scale:.87},{rotationY:0,scale:1,ease:'none',scrollTrigger:{trigger:'.risk-story',start:'top 80%',end:'bottom 30%',scrub:.8}});gsap.fromTo('.infrastructure-art',{rotationX:6,rotationY:9,transformPerspective:1200},{rotationX:0,rotationY:0,ease:'none',scrollTrigger:{trigger:'.services-layout',start:'top 80%',end:'bottom 25%',scrub:.8}})});document.fonts.ready.then(()=>ScrollTrigger.refresh())})();
