(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];gsap.registerPlugin(ScrollTrigger);const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;window.__motionScenes=[];window.__demoState={scenario:0,phase:0};window.__lenis=null;if(!reduce&&window.Lenis){const lenis=window.__lenis=new Lenis({duration:1.15,smoothWheel:true});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0)}
function scene(name,target,vars,trigger,options={}){const el=typeof target==='string'?$(target):target;if(!el)throw Error('Missing scene target '+name);const config={trigger:typeof trigger==='string'?$(trigger):trigger||el,start:'top bottom',end:'bottom top',scrub:1,...options};window.__motionScenes.push({name,target:el.className||el.tagName,trigger:config.trigger.id||config.trigger.className});if(!reduce)gsap.to(el,{...vars,ease:'none',scrollTrigger:config})}
// All animation affects artwork. Copy remains fully opaque and readable.
scene('film inward zoom','.film-stage video',{scale:1.65},'.hero',{start:'top top',end:()=>'+='+innerHeight*1.25,pin:true,anticipatePin:1,invalidateOnRefresh:true});
scene('scroll depth meter','.hero-foot',{x:20},'.hero');scene('media framing','.hero-shade',{scaleY:1.08},'.hero');scene('navigation state','.top',{y:-20},'.hero');
scene('context calendar rise','.calendar-sheet',{y:-38,rotation:-2},'.context');scene('context calendar depth','.calendar-sheet.back',{y:22,rotation:7},'.context');
scene('data intake path','.engine-path',{x:12},'.engine');scene('macro node','.input-list button:nth-of-type(1) b',{rotation:45},'.engine');scene('rates node','.input-list button:nth-of-type(2) b',{rotation:45},'.engine');scene('risk node','.input-list button:nth-of-type(3) b',{rotation:45},'.engine');scene('execution path','.engine-path path',{strokeDashoffset:0},'.engine');scene('platform node','.output-stage i',{scale:1.7},'.engine');
scene('account boundary','.boundary i:first-child',{x:-12,rotation:20},'.control');scene('licence architecture','.licence i:nth-child(2)',{y:-20,rotation:14},'.control');scene('audit path','.audit i:nth-child(2)',{scaleX:.75},'.control');scene('control split','.boundary i:last-child',{x:12,rotation:-20},'.control');
$$('.pipeline article').forEach((a,i)=>scene(['execution pipeline','connector trace','support boundary','architecture depth'][i],a.querySelector('.pipeline-art'),{rotationY:i%2?12:-12,y:-15,transformPerspective:800},a));
scene('timeline travel','.stress-visual canvas',{x:12},'.stress');scene('event focus','.stress-lab',{rotationX:2,transformPerspective:1400},'.stress');scene('state transition','.stress-visual canvas',{filter:'brightness(1.2)'},'.stress');scene('risk threshold','.phase-markers',{y:-8},'.stress');scene('recovery path','.stress-visual canvas',{borderRadius:24},'.stress');scene('scenario depth','.stress-visual',{rotationY:3,transformPerspective:1200},'.stress');
$$('.risk-grid article').forEach((a,i)=>scene(['capital boundary','equity limit','calendar signal','defensive orbit'][i],a.querySelector('.risk-art i'),{rotation:135+(i*20),scale:1.15},a));
$$('.process-list article').forEach((a,i)=>scene(['evaluation path','validation path','walkthrough path','contract path','setup path','activation path','support path'][i],a.querySelector('i'),{scaleX:.25},a));
scene('final orbit','.closing-orbit',{rotationX:50,rotationZ:70,transformPerspective:900},'.closing');scene('contact magnetic response','.closing .button span',{rotation:45},'.closing');
for(const p of $$('.context-line path,.engine-path path')){const l=p.getTotalLength();p.style.strokeDasharray=l;p.style.strokeDashoffset=l*.8}
if(matchMedia('(hover:hover) and (pointer:fine)').matches&&!reduce){$$('.control-grid article,.risk-grid article').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();gsap.to(el,{rotationX:((e.clientY-r.top)/r.height-.5)*-4,rotationY:((e.clientX-r.left)/r.width-.5)*5,transformPerspective:1000,duration:.5})});el.addEventListener('pointerleave',()=>gsap.to(el,{rotationX:0,rotationY:0,duration:.7}))})}
const inputs={macro:['Economic context','An economic release enters the data stage. Predefined rules evaluate it alongside related context before an eligible instruction can reach the execution platform.'],rates:['Rate context','Central bank rates enter the data stage. The rule-processing stage evaluates their currency and economic context before any eligible platform instruction.'],risk:['Risk context','Market-risk inputs enter the data stage. Defined controls are checked in rule processing before an eligible instruction reaches MetaTrader or cTrader.']};$$('[data-input]').forEach(b=>b.addEventListener('click',()=>{$$('[data-input]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const data=inputs[b.dataset.input];$('#input-title').textContent=data[0];$('#input-detail').textContent=data[1];window.__activeInput=b.dataset.input;if(!reduce)gsap.fromTo('.output-stage i',{scale:1},{scale:1.8,duration:.45,yoyo:true,repeat:1})}));
const scenarios=[['Normal conditions','Inputs arrive, checks run, and eligible instructions proceed through the defined workflow.'],['Volatility shock','The illustration routes incoming signals through a risk-control checkpoint before a decision can proceed.'],['Connection interruption','The illustration pauses the execution path while connectivity is reviewed. It is not a verified product behavior.']];$$('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{$$('[data-scenario]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));window.__demoState.scenario=Number(b.dataset.scenario);$('#scenario-title').textContent=scenarios[window.__demoState.scenario][0];$('#scenario-detail').textContent=scenarios[window.__demoState.scenario][1]}));$('#phase').addEventListener('input',e=>{window.__demoState.phase=+e.target.value;$('#phase-name').textContent=+e.target.value<34?'Observe':+e.target.value<67?'Apply controls':'Review'});
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=$(a.getAttribute('href'));if(target){e.preventDefault();window.__lenis?window.__lenis.scrollTo(target,{offset:-35}):target.scrollIntoView({behavior:reduce?'instant':'smooth'})}}));
const film=$('.film-stage video'),filmButton=$('.film-start');film.muted=true;film.defaultMuted=true;film.playsInline=true;
const revealFilm=()=>{filmButton.hidden=false;filmButton.textContent=film.readyState<2?'Load / play film ↗':'Play film ↗'};
const startFilm=()=>{const promise=film.play();if(promise)promise.then(()=>{filmButton.hidden=true}).catch(revealFilm)};
const phone=matchMedia('(max-width:650px)').matches;film.poster=phone?'13-trading-poster-phone.webp':'12-trading-poster-desktop.webp';film.src=phone?'11-trading-hero-phone.mp4':'10-trading-hero-desktop.mp4';film.preload='auto';film.load();
film.addEventListener('canplay',startFilm);film.addEventListener('playing',()=>{filmButton.hidden=true});film.addEventListener('error',revealFilm);film.addEventListener('stalled',revealFilm);
setTimeout(()=>{if(film.paused||film.readyState<2)revealFilm()},2200);
filmButton.addEventListener('click',()=>{if(film.readyState===0)film.load();startFilm()});document.addEventListener('touchstart',startFilm,{once:true,passive:true});document.addEventListener('pointerdown',startFilm,{once:true,passive:true});
window.addEventListener('load',()=>ScrollTrigger.refresh());window.__motionReady=true;})();
