import * as THREE from './9-three.module.min.js';
const canvas=document.getElementById('hero-field'),reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.set(0,0,10);const group=new THREE.Group();scene.add(group);
const aqua=0x88e3dd,teal=0x2f736e;scene.add(new THREE.HemisphereLight(0xd9fff9,0x051013,2.5));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(4,6,5);scene.add(key);const rim=new THREE.PointLight(aqua,25,20);rim.position.set(-3,1,3);scene.add(rim);
function box(w,h,d,r=.08){const s=new THREE.Shape();s.moveTo(-w/2+r,-d/2);s.lineTo(w/2-r,-d/2);s.quadraticCurveTo(w/2,-d/2,w/2,-d/2+r);s.lineTo(w/2,d/2-r);s.quadraticCurveTo(w/2,d/2,w/2-r,d/2);s.lineTo(-w/2+r,d/2);s.quadraticCurveTo(-w/2,d/2,-w/2,d/2-r);s.lineTo(-w/2,-d/2+r);s.quadraticCurveTo(-w/2,-d/2,-w/2+r,-d/2);const g=new THREE.ExtrudeGeometry(s,{depth:h,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.025,bevelThickness:.025});g.rotateX(-Math.PI/2);g.translate(0,-h/2,0);return g}
function face(label,sub){const c=document.createElement('canvas');c.width=1024;c.height=768;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,1024,768);g.addColorStop(0,'#204a46');g.addColorStop(.45,'#0d1e20');g.addColorStop(1,'#173330');x.fillStyle=g;x.fillRect(0,0,1024,768);x.strokeStyle='#4e9790';x.lineWidth=3;x.strokeRect(32,32,960,704);x.fillStyle='#88e3dd';x.font='24px Arial';x.fillText('ARCHITECTURE / DESIGN STUDY',75,110);x.fillStyle='#e8fffc';x.font='bold 78px Arial';x.fillText(label,75,365);x.font='24px Arial';x.fillStyle='#a0cfca';x.fillText(sub,75,425);x.strokeStyle='#32635e';x.lineWidth=2;for(let i=0;i<6;i++){x.beginPath();x.moveTo(75,520+i*23);x.lineTo(500+i*45,520+i*23);x.stroke()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t}
const board=new THREE.Mesh(box(3.8,.09,2.7),new THREE.MeshStandardMaterial({color:0x122d2b,metalness:.7,roughness:.32}));board.position.y=-.5;group.add(board);
const chip=new THREE.Group();chip.position.y=-.05;group.add(chip);chip.add(new THREE.Mesh(box(2.4,.48,1.8),new THREE.MeshPhysicalMaterial({color:teal,metalness:.5,roughness:.2,emissive:aqua,emissiveIntensity:.12})));
const lid=new THREE.Mesh(new THREE.PlaneGeometry(2.36,1.76),new THREE.MeshStandardMaterial({map:face('ENGINE','CONTEXT  /  RULES  /  PLATFORM'),metalness:.35,roughness:.3}));lid.rotation.x=-Math.PI/2;lid.position.y=.30;chip.add(lid);
const pins=new THREE.MeshStandardMaterial({color:0xa5c8c3,metalness:.9,roughness:.17});for(let i=0;i<14;i++){for(const z of [-1,1]){const pin=new THREE.Mesh(new THREE.BoxGeometry(.075,.1,.25),pins);pin.position.set(-1.05+i*.16,-.12,z);chip.add(pin)}}
const traces=[],packets=[];for(let i=0;i<7;i++){const x=-1.45+i*.48,curve=new THREE.CatmullRomCurve3([new THREE.Vector3(x,-.44,1.28),new THREE.Vector3(x,-.44,.95),new THREE.Vector3(x*.55,-.44,.68),new THREE.Vector3(x*.55,-.44,-.68),new THREE.Vector3(x,-.44,-1.28)]);group.add(new THREE.Mesh(new THREE.TubeGeometry(curve,32,.012,6,false),new THREE.MeshBasicMaterial({color:aqua,transparent:true,opacity:.5})));const dot=new THREE.Mesh(new THREE.SphereGeometry(.035,8,8),new THREE.MeshBasicMaterial({color:0xd5fff7}));group.add(dot);traces.push(curve);packets.push(dot)}
const satellites=[];for(let i=0;i<2;i++){const unit=new THREE.Group();unit.position.set(i?1.9:-1.9,.45,i?.85:-.85);const m=new THREE.Mesh(box(.92,.16,.66,.04),new THREE.MeshStandardMaterial({color:0x17433d,metalness:.6,roughness:.2}));unit.add(m);const tag=new THREE.Mesh(new THREE.PlaneGeometry(.9,.64),new THREE.MeshStandardMaterial({map:face(i?'CONTROL':'SIGNAL',i?'DEFINED LIMITS':'ECONOMIC CONTEXT'),roughness:.35}));tag.rotation.x=-Math.PI/2;tag.position.y=.12;unit.add(tag);group.add(unit);satellites.push(unit)}
let pointer={x:0,y:0};document.querySelector('.hero').addEventListener('pointermove',e=>{pointer.x=(e.clientX/innerWidth-.5)*.3;pointer.y=(e.clientY/innerHeight-.5)*.15});
function size(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();const phone=innerWidth<650;group.position.set(phone?.5:2.3,phone?-1.7:-.3,0);group.scale.setScalar(phone?.68:1.16);group.rotation.set(.52,-.28,-.06);satellites.forEach(u=>u.visible=!phone)}new ResizeObserver(size).observe(canvas);size();let time=0;
function tick(){time+=.01;if(!reduce){group.rotation.y+=(-.28+pointer.x-group.rotation.y)*.025;group.rotation.x+=(.52+pointer.y-group.rotation.x)*.025;chip.position.y=-.05+Math.sin(time*.4)*.045;packets.forEach((p,i)=>p.position.copy(traces[i].getPointAt((time*.05+i*.11)%1)));satellites.forEach((s,i)=>s.position.y=.45+Math.sin(time*.6+i)*.04)}renderer.render(scene,camera);window.__webglRendered=true;if(!reduce)requestAnimationFrame(tick)}tick();
const stress=document.getElementById('stress-field'),ctx=stress.getContext('2d');function draw(){const r=stress.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);if(stress.width!==Math.round(r.width*d)||stress.height!==Math.round(r.height*d)){stress.width=r.width*d;stress.height=r.height*d}ctx.setTransform(d,0,0,d,0,0);const state=window.__demoState||{scenario:0,phase:0},phase=state.phase/100;ctx.clearRect(0,0,r.width,r.height);ctx.strokeStyle='#88e3dd';ctx.lineWidth=1.2;const left=innerWidth>650?r.width*.43:r.width*.08,right=r.width*.94,mid=innerWidth>650?r.height*.5:r.height*.27;ctx.globalAlpha=.24;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(left,mid+(i-2)*20);ctx.lineTo(right,mid+(i-2)*20);ctx.stroke()}ctx.globalAlpha=.8;ctx.beginPath();for(let i=0;i<=60;i++){let x=left+(right-left)*i/60,y=mid+Math.sin(i*.22+phase*2)*12;if(state.scenario===1)y+=Math.sin(i*.65)*28;if(state.scenario===2&&i>30)y=mid;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();const x=left+(right-left)*phase;ctx.beginPath();ctx.arc(x,mid,5,0,Math.PI*2);ctx.fillStyle='#88e3dd';ctx.fill();ctx.setLineDash([3,6]);ctx.globalAlpha=.4;ctx.strokeRect(left,mid-70,right-left,140);ctx.setLineDash([]);if(!reduce)requestAnimationFrame(draw)}draw();window.__fieldReady=true;
