const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches,canvas=document.getElementById('stress-field'),ctx=canvas.getContext('2d');
let visible=true;new IntersectionObserver(e=>visible=e[0].isIntersecting).observe(canvas);window.__stressFrames=0;
function draw(t=0){if(visible){const b=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(b.width*d)||canvas.height!==Math.round(b.height*d)){canvas.width=b.width*d;canvas.height=b.height*d}ctx.setTransform(d,0,0,d,0,0);const w=b.width,h=b.height,state=window.__demoState||{scenario:0,phase:0},s=reduce?0:t*.0002,phase=state.phase/100,shock=state.scenario===1,paused=state.scenario===2,cx=w*.55,cy=h*.43,R=Math.min(w*.33,h*.3);ctx.clearRect(0,0,w,h);
const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,R*1.8);glow.addColorStop(0,shock?'#8e68452a':'#65e2d929');glow.addColorStop(1,'#0b151700');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
ctx.save();ctx.translate(cx,cy);ctx.rotate(-.28);ctx.scale(1,.58);for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(0,0,R*(.65+i*.2),R*(.65+i*.2),0,0,Math.PI*2);ctx.strokeStyle=i===2?(paused?'#d1a379':'#88e3dd'):'#315d59';ctx.lineWidth=i===2?3:1;ctx.stroke()}ctx.restore();
for(let i=0;i<100;i++){let progress=paused?(i/100):((i/100+s*.7)%1),a=i*2.39996+s*(shock?2:.4),r=R*(1.6-progress*1.2),x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r*.54;const alpha=.25+progress*.6;ctx.fillStyle=shock?`rgba(228,182,125,${alpha})`:`rgba(151,238,225,${alpha})`;ctx.beginPath();ctx.arc(x,y,i%7===0?3.5:1.5,0,Math.PI*2);ctx.fill()}
ctx.save();ctx.translate(cx,cy);ctx.rotate(s*.25);for(let j=0;j<3;j++){const rr=R*(.21+j*.09);ctx.beginPath();for(let i=0;i<6;i++){let a=i*Math.PI/3+j*.2;const x=Math.cos(a)*rr,y=Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fillStyle=j===0?'#163e3b':'#1b494655';ctx.fill();ctx.strokeStyle='#90dcd2';ctx.lineWidth=1.2;ctx.stroke()}ctx.restore();
ctx.fillStyle='#e3f1ed';ctx.font='600 12px Manrope,Arial';ctx.textAlign='center';ctx.fillText(paused?'REVIEW':shock?'CONTROL':'OBSERVE',cx,cy+5);
const steps=['INPUT','CONTROL','REVIEW'];steps.forEach((text,i)=>{const x=w*(.2+i*.3),y=h*.78,active=phase>i/3;ctx.strokeStyle=active?'#88e3dd':'#476d66';ctx.lineWidth=active?2:1;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#cce7e2';ctx.font='11px Manrope,Arial';ctx.fillText(text,x,y+27);if(i<2){ctx.strokeStyle='#355a54';ctx.beginPath();ctx.moveTo(x+12,y);ctx.lineTo(x+w*.3-12,y);ctx.stroke()}});window.__stressFrames++}if(!reduce)requestAnimationFrame(draw)}draw();window.__fieldReady=true;
